#ifndef APP_CFG_H
#define APP_CFG_H

#include "FreeRTOS.h"
#include "task.h"

#define APP_SENSOR_TASK_STACK_SIZE 256U
#define APP_SENSOR_TASK_PRIORITY   (tskIDLE_PRIORITY + 2U)
#define APP_SENSOR_TASK_PERIOD_MS  10U
#define APP_SENSOR_TASK_HB_BIT (1 << 0U)

#define APP_COMM_TASK_STACK_SIZE 512U
#define APP_COMM_TASK_PRIORITY   (tskIDLE_PRIORITY + 1U)
#define APP_COMM_TASK_PERIOD_MS  1000U
#define APP_COMM_TASK_HB_BIT (1 << 2U)

#define APP_SUPERVISOR_TASK_STACK_SIZE 256U
#define APP_SUPERVISOR_TASK_PRIORITY   ((configMAX_PRIORITIES - 1U) | portPRIVILEGE_BIT)
#define APP_SUPERVISOR_TASK_PERIOD_MS  10U

#define APP_CONTROL_TASK_STACK_SIZE 256U
#define APP_CONTROL_TASK_PRIORITY   (tskIDLE_PRIORITY + 3U)
#define APP_CONTROL_TASK_PERIOD_MS  5U
#define APP_CONTROL_TASK_HB_BIT (1 << 1U)

#define APP_MONITOR_TASK_STACK_SIZE 256U
#define APP_MONITOR_TASK_PRIORITY (tskIDLE_PRIORITY + 1U)
#define APP_MONITOR_TASK_PERIOD_MS 1000U

#define APP_WATCHDOG_TIMEOUT_MS 15U


#define INJECT_TASK_OVER_PERIOD
#undef INJECT_TASK_OVER_PERIOD

#define INJECT_LONG_INTERRUPT_HANDLE
#undef INJECT_LONG_INTERRUPT_HANDLE

#endif /* APP_CFG_H */