#ifndef APP_CFG_H
#define APP_CFG_H

#include "FreeRTOS.h"
#include "task.h"

#define APP_SENSOR_TASK_STACK_SIZE 256U
#define APP_SENSOR_TASK_PRIORITY   (tskIDLE_PRIORITY + 2U)
#define APP_SENSOR_TASK_PERIOD_MS  10U

#define APP_COMM_TASK_STACK_SIZE 256U
#define APP_COMM_TASK_PRIORITY   (tskIDLE_PRIORITY + 1U)
#define APP_COMM_TASK_PERIOD_MS  500U

#define APP_SUPERVISOR_TASK_STACK_SIZE 256U
#define APP_SUPERVISOR_TASK_PRIORITY   ((configMAX_PRIORITIES - 1U) | portPRIVILEGE_BIT)
#define APP_SUPERVISOR_TASK_PERIOD_MS  10U

#define APP_CONTROL_TASK_STACK_SIZE 256U
#define APP_CONTROL_TASK_PRIORITY   (tskIDLE_PRIORITY + 3U)
#define APP_CONTROL_TASK_PERIOD_MS  5U

#endif /* APP_CFG_H */